### ISSUE TITLE
fhir-qb/mongo: buildSearchQuery(req, configs) fails when 'req' has unknown parameter(not defined in configs)

### ISSUE THREAD

**Issue by navndn** [Asymmetrik/phx-tools#18]
Version:
 "@asymmetrik/fhir-qb": "^0.10.3"

It seems like `buildSearchQuery(req, configs)` fails/aborts when `req` has an unknown(not defined in `configs`) parameter.  Side effect of this is that it fails all the times for express `req` object as  express `req.params` contains `base_version` parameter which is of no interest for mongo query and hence not defined in `configs`.

Isn't it more convenient/usable if fhir-qb ignores undefined params? 

Thanks!

**Comment by sshah-asymmetrik** [comment]
Hello!

Our main reason for rejecting/failing requests instead of just ignoring them that contain unknown and undefined search parameters is that we don't want users to get results back under the impression that they've been filtered on these undefined search params. Users would have no way of immediately knowing that their query was invalid. Unfortunately the FHIR spec for Bundles does not have any fields where we could include warnings.

In order to get around extra parameters, in our core server we enable the addition of custom search parameters into the definitions. A good place to start for that would be (https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/server/utils/params.utils.js). We would recommend adding a custom parameter definition for base_version, as otherwise users won't be alerted to invalid search params.

Please let us know if you have additional questions!
Thanks!

**Comment by navndn** [comment]
@sshah-asymmetrik , Makes sense.  

But I don't think I fully understand your first work-around for `base_version`  i.e adding a custom parameter definition.  
`buildSearchQuery(req, configs)`  method expects param definitions in `configs` to have `xpath` property but there is no fhirpath for `base_version` parameter right? Making its value `''` or just `Resource` 
```
    base_version: {
        type: 'string',
        fhirtype: 'string',
        xpath: '',
    },

```

would result in unwanted mongo query for `base_version` as below:

```
[
  {
    "$match": {
      "$and": [
        {
          "$or": [
            {
              "undefined": {
                "$regex": "^4_0_0",
                "$options": "i"
              }
            }
          ]
        }
      ]
    }
  }
]
```


Sorry, What am I missing here?
Thanks.

**Comment by sshah-asymmetrik** [comment]
Hmmm, I took a second look at this, and I believe you are correct. The first work-around of making a custom parameter definition would not work for `base_version`, as the resources themselves do not contain this property, and the query builder will still attempt to search on them using this property.

With that in mind, we would still recommend the second work-around (removing `base_version` from the request params) over simply ignoring unknown request parameters, which opens up the door to having silent failures. If you're currently using `base_version` as a req parameter to determine which version of a resource to use, it might be better to instead make the base version part of the base url, and handle the versioning decision through express routes instead of adding it to the request params.

This is how we handle resource versioning in `node-fhir-server-core`. If you take a look at (https://github.com/Asymmetrik/node-fhir-server-core/blob/master/src/server/router.js), it shows how we avoid adding anything extra to url query params and handle resource versions by parsing it out of the main url instead.

**Comment by navndn** [comment]
Yes. I'll be using the second option, i.e using a trimmed version of `req` object by removing unwanted parameters from `req.query/params/body` --  `base_version` and complex params/fhirtypes like address, HumanName for which fhir-qb/mongo doesn't yet provide a complete query(I might need to build query from scratch for these and merge with fhir-qb's query)

> If you're currently using base_version as a req parameter to determine which version of a resource to use, it might be better to instead make the base version part of the base url, and handle the versioning decision through express routes instead of adding it to the request params.

My current situation is similar to this .. https://github.com/Asymmetrik/node-fhir-server-mongo/blob/master/src/services/patient/patient.service.js#L417
Not sure separate {resource}.service.js for each version is feasible.

My express request, `context.req`(with server-core 2.0.1 ) looks like this 
```
{
   "method": "GET",
   "query": {
     "active": "true",
     "identifier": "R-1240",
     "birthdate": "1950-01"
   },
   "params": {
     "base_version": "4_0_0"
   },
   "sanitized_args": {
     "base_version": "4_0_0",
     "active": "true",
     "birthdate": "1950-01",
     "identifier": "R-1240"
   },
   "originalUrl": "/4_0_0/Patient?active=true&identifier=R-1240&birthdate=1950-01"
 }
```

**Comment by sshah-asymmetrik** [comment]
Sounds good! If this is what your current request looks like, the issue should be solved by trimming `base_version` from your params. As you said, we don't currently support much for complex fhirtypes. Often, fields of types like HumanName fall under other categories according to the structure definitions. Using HumanName for a patient, its type in the structure definition is a simple string, which gets defined in the 'type' field of the definition. Currently (this is a stopgap measure), we only use the fhirtype field for further defining 'token' fields, as there are a couple different kinds of token that the definitions otherwise fail to differentiate.

**Comment by navndn** [comment]
Hey @sshah-asymmetrik,  one more thing.. 
I know `buildsarchQuery` supports date/time search against single Date/Time fhirpath.. Does it also support date/time range search on `Period` fhirtype i.e  find whther there's a non-empty intersection between the period specified in the search and the period specified in the resource(ex: `Encounter.period`) ? 
If not, do you have any suggestions/easy-hacks involving fhir-qb/QueryBuilder's methods?

**Comment by sshah-asymmetrik** [comment]
We don't specifically support the `Period` fhirtype, but we may have something that gets you the behavior that you need. `Period` params are composed of a `start` date and an `end` date. You could build a query around either the start or end date with our query builder. As these periods are generally optional, you would likely have to add in a custom parameter definition as described above.

For example, using an example patient from the HL7 site (https://www.hl7.org/fhir/patient-example.json.html), you could add a custom parameter definition for the `period` field in the `identifier` list of objects (and any of the other ones as needed). For this one, the definition would look something like:

```
{
    identifier-period-start: {
        type: 'date',
        fhirtype: 'date',
        xpath: 'Patient.identifier.period.start',
        definition: 'http://hl7.org/fhir/patient.html',
        description: 'The start of the period for which the identifier is valid',
        modifier: 'missing'
    }
}
```
With this, you could do range queries on the period field. The one below is a query on this period field for dates greater than the 2010-01-01 and less than 2011-01-01:
```
<Base URL>/4_0_0/Patient?identifier-period-start=ge2010-01-01&identifier-period-start=le2010-01-01
```

**Comment by navndn** [comment]
Yes, that's my plan too - custom param(date-start/end) on start/end dates. It is an easy close alternative for official Encounter search parameter `date`  which corresponds to fhirpath `Encounter.period`.. https://www.hl7.org/fhir/encounter.html#search 

Official `date` param:
```
<Base URL>/4_0_0/Encounter?date={lowerDate}&date={upperDate}
```
implies following

`((Encounter.period.start > {lowerDate} || Encounter.period.end > {lowerDate}) && (Encounter.period.start < {upperDate} || Encounter.period.end < {upperDate}))`

and requires quite a bit of work if I can't leverage fhir-qb's date processing(prefix, implicit range).
