### ISSUE TITLE
fhir-qb/mongo: Is it possible to configure param definition to generate '$or' query against 2 target xpaths from one search parameter

### ISSUE THREAD

**Issue by navndn** [Asymmetrik/phx-tools#21]
`Location` resource has a [search parameter](https://www.hl7.org/fhir/location.html#search) called `name` whose target can be `Location.name` or `Location.alias`. 
Is it possible to achieve this using fhir-qb? 

Possible feature request, how about a config like this?

```
    name: {
        type: 'string',
        fhirtype: 'string',
        xpath: 'Resource.name, Resource.alias'
    },

```
Thanks!

**Comment by sshah-asymmetrik** [comment]
Hi @navndn,
Sorry for the delayed response! Things have been very hectic recently.
This should be possible and will be a good feature addition, but is not currently possible with the existing code. Thank you for bringing this to our attention! 

I have added a ticket to our backlog to add this feature. However, due to the current distribution of work and an upcoming conference, it may be a bit before we can actually get this implemented.

**Comment by navndn** [comment]
@sshah-asymmetrik,  Sounds good. Thanks you

**Comment by sshah-asymmetrik** [comment]
@navndn 

Looks like this feature was simpler than expected. I had a lull in my schedule and was able to take care of it. If you're interested in the actual implementation, take a look at the pull request at https://github.com/Asymmetrik/phx-tools/pull/22.

The only real difference between your suggestion and the implementation is that the implementation will optionally take a list as the xpath instead of comma delimited string.
```
    name: {
        type: 'string',
        fhirtype: 'string',
        xpath: ['Resource.name', 'Resource.alias']
    },
```

**Comment by navndn** [comment]
@sshah-asymmetrik This is awesome! Just saw your PR.

**Comment by navndn** [comment]
@sshah-asymmetrik when do think this would be part of npm package release?

**Comment by sshah-asymmetrik** [comment]
We're hoping to get this reviewed and deployed this afternoon!

**Comment by sshah-asymmetrik** [comment]
Published!
